apiVersion: v1
kind: PersistentVolume
metadata:
  name: meteor-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/meteor"
