apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  nfs: 
    path: /var/nfs/general/data
    server: 157.230.238.156
