apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: sameersbn/redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /var/lib/redis
          name: redis-pv
      volumes:
      - name: redis-pv
        persistentVolumeClaim:
           claimName: redis-pvc
      restartPolicy: Always
